# gui/translator.py

import json
import os
import re

from PyQt6.QtCore import QObject, pyqtSignal


def translate_violation_reason(reason):
    """
    将后端输出的中文违规原因翻译为当前语言。
    支持多子句（以分号分隔），每个子句独立翻译。
    """
    if not reason:
        return ""

    # 定义子句模式到翻译键的映射（注意捕获动态部分）
    clause_patterns = [
        (r'违反IP地址范围规则', 'violation_ip_range', []),  # 无动态部分
        (r'协议类型(\d+)违反规则', 'violation_protocol', ['{0}']),
        (r'源端口(\d+)违反规则', 'violation_src_port', ['{0}']),
        (r'目的端口(\d+)违反规则', 'violation_dst_port', ['{0}']),
        (r'与([\d\.]+)的通信流量为(\d+) bytes，超过了最大流量阈值(\d+) bytes',
         'violation_traffic', ['{0}', '{1}', '{2}']),  # IP, traffic, maxTraffic
    ]

    # 分割子句（按分号，并去除前后空格）
    clauses = [c.strip() for c in reason.split(';') if c.strip()]
    translated_clauses = []

    for clause in clauses:
        matched = False
        for pattern, key, placeholders in clause_patterns:
            m = re.search(pattern, clause)
            if m:
                # 获取翻译模板
                template = tr(key, key)  # 第二个参数作为默认，实际应从字典取
                # 如果有动态部分，用捕获组填充
                if placeholders:
                    # 将捕获组转换为列表，并格式化
                    args = list(m.groups())
                    # 注意：对于 violation_traffic，捕获组顺序为 IP, traffic, maxTraffic
                    # 模板中应包含对应数量的 {} 占位符
                    translated = template.format(*args)
                else:
                    translated = template
                translated_clauses.append(translated)
                matched = True
                break
        if not matched:
            # 如果无法匹配，保留原句（或记录警告）
            translated_clauses.append(clause)

    # 用分号重新连接
    return '；'.join(translated_clauses)


def translate_backend_output(line):
    """将后端输出的中文提示翻译为当前语言"""
    # 定义中文模式到翻译键的映射
    patterns = [
        (r'全网拓扑已导出到 (.*)', 'full_graph_exported'),
        (r'子图已导出到 (.*)', 'subgraph_exported'),
        (r'检测到端口扫描攻击者 (\d+) 个:', 'port_scan_detected'),
        (r'检测到DDoS攻击目标 (\d+) 个:', 'ddos_target_detected'),
        (r'找到星型结构 (\d+) 个:', 'star_structure_found'),
        (r'违反规则的通信记录 (\d+) 条:', 'custom_rule_violations'),
        (r'路径子图已导出到 (.*)', 'path_subgraph_exported'),
        (r'对比路径子图已导出到 (.*)', 'compare_paths_subgraph_exported'),
        (r'端口扫描攻击者子图已导出到 (.*)', 'port_scan_subgraph_exported'),
        (r'DDoS攻击目标子图已导出到 (.*)', 'ddos_subgraph_exported'),
        (r'星型结构子图已导出到 (.*)', 'star_subgraph_exported'),
        (r'违规通信子图已导出到 (.*)', 'custom_rule_subgraph_exported'),
        (r'没有找到从 (.*) 到 (.*) 的路径', 'no_path_found'),
        (r'最小拥塞路径 \(共 (\d+) 条\):', 'min_congestion_paths'),
        (r'最小跳数路径 \(最小跳数 = (\d+)\):', 'min_hop_paths'),
        (r'最小风险路径 \(最小风险值 = ([\d.]+)\):', 'min_risk_paths'),
        (r'【最小拥塞路径】', 'min_congestion_section'),
        (r'【最小跳数路径】', 'min_hop_section'),
        (r'【最小风险路径】', 'min_risk_section'),
        (r'  无违规记录', 'no_violations'),
        # 错误信息（若后端输出错误时也包含中文）
        (r'错误: (.*)', 'error_prefix'),
        (r'警告: (.*)', 'warning_prefix'),
    ]
    for pattern, key in patterns:
        match = re.search(pattern, line)
        if match:
            groups = match.groups()
            if not groups:
                # 无动态部分，直接返回翻译
                return tr(key, key)
            else:
                # 有动态部分，用翻译模板格式化
                # 注意：翻译模板应包含对应数量的 {} 占位符
                translated = tr(key, key)
                try:
                    return translated.format(*groups)
                except IndexError:
                    # 如果占位符数量不匹配，返回原行
                    return line
    return line  # 无匹配则返回原行


# 翻译字典
TRANSLATIONS = {
    "zh_CN": {
        "app_title": "网络流量分析与异常检测系统",
        "waiting_data": "等待分析数据...",
        "waiting_data_loading": "等待数据加载...",
        "warning": "警告",
        "src_port_int": "源端口必须为整数",
        "dst_port_int": "目的端口必须为整数",
        "max_traffic_int": "最大流量阈值必须为整数",
        "settings": "设置",
        "help": "帮助",
        "about": "关于",
        "help_manual": "用户手册",
        "language": "语言 / Language",
        "lang_zh_CN": "简体中文",
        "lang_zh_TW": "繁体中文",
        "lang_en_US": "English",
        "restart_required": "语言切换成功，部分界面（如已加载的数据标签页）可能需要重启应用才能完全生效。",
        "info": "提示",
        "invalid_data": "数据无效",
        "data_not_loaded": "未加载任何数据文件，请先加载有效数据！",
        "empty_file": "加载的文件为空，请重试！",
        "no_valid_network_data": "加载的文件无有效网络流量数据，请重试！",
        "file": "文件",
        "browse": "浏览...",
        "data_file": "数据文件:",
        "open_file": "打开数据文件",
        "thread_count": "线程数:",
        "traffic_sorting": "流量排序",
        "path_search": "路径查找",
        "anomaly_detection": "异常检测",
        "subgraph_visualization": "子图可视化",
        "sort_type_label": "排序类型:",
        "flow_sort_total": "总流量",
        "flow_sort_https": "HTTPS",
        "flow_sort_outratio": "出流量",
        "outratio_threshold_label": "出流量占比阈值:",
        "flow_sort_button": "执行流量排序",
        "path_type_label": "路径类型:",
        "path_min_congestion": "最小拥塞",
        "path_min_hop": "最小跳数",
        "path_min_risk": "最小风险",
        "src_ip_label": "源IP:",
        "dst_ip_label": "目的IP:",
        "compare_strategies_checkbox": "对比三种策略",
        "path_search_button": "查找路径",
        "output_log_tab": "⚙️ 运行日志",
        "output_table_tab": "📊 数据表格",
        "output_detail_tab": "🗺️ 路径与详情",
        "anomaly_tab_port_scan": "端口扫描",
        "anomaly_tab_ddos": "DDoS目标",
        "anomaly_tab_star": "星型结构",
        "anomaly_tab_custom_rule": "自定义规则",
        "port_scan_threshold_label": "端口数阈值:",
        "port_scan_button": "检测",
        "ddos_neighbor_threshold_label": "邻居数阈值:",
        "ddos_traffic_threshold_label": "入流量阈值:",
        "ddos_traffic_placeholder": "例如：1024",
        "ddos_unit_bytes": "字节",
        "ddos_button": "检测",
        "star_threshold_label": "叶子节点数阈值:",
        "star_button": "检测",
        "subgraph_target_ip_label": "目标IP:",
        "subgraph_generate_button": "生成子图",
        "open_file_dialog_title": "选择数据文件",
        "file_filter": "支持的文件 (*.csv *.pcap *.json *.html);;CSV (*.csv);;PCAP (*.pcap);;JSON (*.json);;HTML (*.html)",
        "encoding_conversion_failed": "文件编码转换失败，无法加载！",
        "analyzing_data": "正在分析数据，请稍候...",
        "loaded_file": "已加载文件: {}",
        "parsing_pcap": "正在解析 PCAP 文件，请稍候...",
        "no_valid_ipv4_data": "PCAP 文件未提取到有效 IPv4 数据",
        "error": "错误",
        "data_validity_check_failed": "检查数据有效性失败: {}",
        "task_start": "[{}] 🚀 开始执行任务: {}",
        "command_line": "[{}] 命令行: {}",
        "task_complete": "\n[{}] ✅ 任务执行完成！正在解析结果...",
        "task_full_graph": "全网拓扑",
        "task_subgraph": "子图",
        "task_flow_sort": "流量排序",
        "task_min_congestion": "最小拥塞路径",
        "task_min_hop": "最小跳数路径",
        "task_min_risk": "最小风险路径",
        "task_compare_paths": "路径对比",
        "task_port_scan": "端口扫描检测",
        "task_ddos_target": "DDoS目标检测",
        "task_star_structures": "星型结构查找",
        "task_custom_rule": "自定义规则检测",
        "custom_rule_table_header_src_ip": "源IP",
        "custom_rule_table_header_dst_ip": "目的IP",
        "custom_rule_table_header_protocol": "协议类型",
        "custom_rule_table_header_src_port": "源端口",
        "custom_rule_table_header_dst_port": "目的端口",
        "custom_rule_table_header_reason": "违规原因",
        "flow_sort_table_header_ip": "IP地址",
        "flow_sort_table_header_total_traffic": "总流量（字节）",
        "flow_sort_table_header_https_traffic": "HTTPS流量（字节）",
        "flow_sort_table_header_out_ratio": "出流量占比",
        "port_scan_table_header_ip": "IP地址",
        "port_scan_table_header_port_count": "不同目的端口数",
        "star_table_header_center_ip": "中心IP",
        "star_table_header_neighbor_count": "邻居叶子数",
        "star_table_header_total_traffic": "总流量",
        "path_detail_title": "🔎 路径分析结果",
        "path_detail_congestion_label": "拥塞值: {}",
        "path_detail_hop_label": "跳数: {}",
        "path_detail_risk_label": "风险值: {}",
        "path_found_count_congestion": "共找到 {} 条最小拥塞路径：",
        "path_found_count_hop": "最小跳数为 {}，共找到 {} 条路径：",
        "path_found_count_risk": "最小风险值为 {}，共找到 {} 条路径：",
        "path_detail_not_found": "未找到符合条件的路径。",
        "compare_paths_detail_title": "🔎 路径对比结果",
        "compare_paths_min_hop_display": "最小跳数: {}",
        "compare_paths_min_risk_display": "最小风险值: {}",
        "compare_paths_table_header_strategy": "策略",
        "compare_paths_table_header_count": "路径数量",
        "compare_paths_table_header_congestion_range": "拥塞值范围(Min ~ Max)",
        "compare_paths_strategy_min_congestion": "最小拥塞",
        "compare_paths_strategy_min_hop": "最小跳数",
        "compare_paths_strategy_min_risk": "最小风险",
        "compare_paths_not_found": "未找到符合条件的路径。",
        "compare_paths_congestion_label": "拥塞值: {}",
        "generate_html_json_invalid": "错误：JSON 文件无效或未能成功生成。",
        "generate_html_theme_invalid": "无法生成图表（JSON 文件无效）",
        "generate_html_no_nodes": "图中无任何节点，可能是数据文件中未包含有效 IP 地址。",
        "generate_html_theme_no_data": "图中无数据",
        "generate_html_read_failed": "读取 JSON 文件失败: {}",
        "generate_html_parse_failed": "解析 JSON 失败",
        "generate_html_rendering": "正在渲染图表，请稍候...",
        "generate_html_success": "图表渲染完成！",
        "generate_html_load_failed": "加载 HTML 失败: {}",
        "replace_cdn_error": "替换CDN链接时出错: {}",
        "display_html_file_not_exist": "错误：HTML 文件不存在 - {}",
        "display_html_success": "子图已加载……",
        "display_html_failed_try_browser": "加载 HTML 失败: {}，正在使用系统浏览器打开",
        "display_html_opened_in_browser": "子图已在系统浏览器中打开",
        "about_content": "网络流量分析与异常检测系统\n华中科技大学网络空间安全学院 - 程序设计综合课程设计\n版本 1.0 | 2026年3月\n基于C++和PyQt6\n ©2026 那，边。版权所有。",
        "path_search_warning_title": "警告",
        "path_search_need_src_dst": "请输入源IP和目的IP",
        "ddos_warning_title": "警告",
        "ddos_traffic_must_be_int": "入流量阈值必须为整数",
        "subgraph_warning_title": "警告",
        "subgraph_need_target_ip": "请输入目标IP",
        "subgraph_generating": "正在生成以 {} 为中心的子图...",
        "custom_rule_target_ip_label": "目标IP:",
        "custom_rule_target_ip_placeholder": "例如：192.168.1.100",
        "custom_rule_ip_range_group": "IP范围",
        "custom_rule_radio_cidr": "CIDR",
        "custom_rule_cidr_placeholder": "例如：192.168.1.0/24",
        "custom_rule_radio_start_end": "起始IP - 结束IP",
        "custom_rule_start_ip_placeholder": "起始IP",
        "custom_rule_to_label": "至",
        "custom_rule_end_ip_placeholder": "结束IP",
        "custom_rule_type_label": "规则类型:",
        "custom_rule_type_deny": "拒绝",
        "custom_rule_type_allow": "允许",
        "custom_rule_optional_group": "可选参数",
        "custom_rule_src_port_label": "源端口:",
        "custom_rule_src_port_placeholder": "例如：443",
        "custom_rule_dst_port_label": "目的端口:",
        "custom_rule_dst_port_placeholder": "例如：80",
        "custom_rule_max_traffic_label": "最大流量阈值:",
        "custom_rule_max_traffic_placeholder": "例如：1024",
        "custom_rule_unit_bytes": "字节",
        "custom_rule_button": "检测违规记录",
        "custom_rule_warning_title": "警告",
        "custom_rule_need_target_ip": "请输入目标IP",
        "custom_rule_need_cidr": "请输入CIDR范围",
        "custom_rule_need_start_end": "请输入起始IP和结束IP",
        "custom_rule_protocol_label": "协议类型:",
        "custom_rule_protocol_placeholder": "例如：6 (TCP)",
        "custom_rule_protocol_int": "协议类型必须为整数",
        "custom_rule_protocol_range": "协议类型必须是0-255之间的整数",
        "custom_rule_src_port_int": "源端口必须为整数",
        "custom_rule_dst_port_int": "目的端口必须为整数",
        "custom_rule_max_traffic_int": "最大流量阈值必须为整数",
        "full_graph_exported": "全网拓扑已导出到 {}",
        "subgraph_exported": "子图已导出到 {}",
        "port_scan_detected": "检测到端口扫描攻击者 {} 个:",
        "ddos_target_detected": "检测到DDoS攻击目标 {} 个:",
        "ddos_table_header_in_data": "入流量（字节）",
        "ddos_table_header_neighbor_count": "邻居数",
        "star_structure_found": "找到星型结构 {} 个:",
        "custom_rule_violations": "违反规则的通信记录 {} 条:",
        "path_subgraph_exported": "路径子图已导出到 {}",
        "compare_paths_subgraph_exported": "对比路径子图已导出到 {}",
        "port_scan_subgraph_exported": "端口扫描攻击者子图已导出到 {}",
        "ddos_subgraph_exported": "DDoS攻击目标子图已导出到 {}",
        "star_subgraph_exported": "星型结构子图已导出到 {}",
        "custom_rule_subgraph_exported": "违规通信子图已导出到 {}",
        "no_path_found": "没有找到从 {} 到 {} 的路径",
        "min_congestion_paths": "最小拥塞路径 (共 {} 条):",
        "min_hop_paths": "最小跳数路径 (最小跳数 = {}):",
        "min_risk_paths": "最小风险路径 (最小风险值 = {}):",
        "min_congestion_section": "【最小拥塞路径】",
        "min_hop_section": "【最小跳数路径】",
        "min_risk_section": "【最小风险路径】",
        "no_violations": "  无违规记录",
        "error_prefix": "错误: {}",
        "warning_prefix": "警告: {}",
        "subgraph_error_file_not_found": "错误：找不到文件 {}",
        "subgraph_error_json_corrupted": "错误：JSON 格式损坏",
        "edge_traffic_title": "流量: {}",
        "violation_ip_range": "违反IP地址范围规则",
        "violation_protocol": "协议类型{}违反规则",
        "violation_src_port": "源端口{}违反规则",
        "violation_dst_port": "目的端口{}违反规则",
        "violation_traffic": "与{}的通信流量为{} bytes，超过了最大流量阈值{} bytes",
        "view_only_mode_no_analysis": "当前处于可视化查看模式，无法进行分析操作。",
        "prepare_html_failed": "准备HTML显示文件失败: {}",
        "visual_file_loaded": "已加载可视化文件: {}",
        "file_not_available": "要导出的文件不可用，请先生成对应图。",
        "save_file": "保存文件",
        "{}_files": "{}文件 (*{})",
        "export_menu": "导出",
        "export_pcap_csv": "PCAP转换的CSV",
        "export_current_subgraph": "当前子图",
    },
    "zh_TW": {
        "app_title": "網路流量分析與異常偵測系統",
        "waiting_data": "等待分析資料...",
        "waiting_data_loading": "等待資料加載...",
        "warning": "警告",
        "src_port_int": "來源埠必須為整數",
        "dst_port_int": "目的埠必須為整數",
        "max_traffic_int": "最大流量閾值必須為整數",
        "settings": "設定",
        "help": "幫助",
        "about": "關於",
        "help_manual": "使用者手冊",
        "language": "語言 / Language",
        "lang_zh_CN": "簡體中文",
        "lang_zh_TW": "繁體中文",
        "lang_en_US": "English",
        "restart_required": "語言切換成功，部分介面（如已載入的資料標籤頁）可能需要重啟應用程式才能完全生效。",
        "info": "提示",
        "invalid_data": "資料無效",
        "data_not_loaded": "未加載任何數據文件，請先加載有效數據！",
        "empty_file": "載入的檔案為空，請重試！",
        "no_valid_network_data": "載入的檔案無有效網路流量數據，請重試！",
        "file": "檔案",
        "browse": "瀏覽...",
        "data_file": "數據檔案:",
        "open_file": "打開數據檔案",
        "thread_count": "執行緒數:",
        "traffic_sorting": "流量排序",
        "path_search": "路徑搜尋",
        "anomaly_detection": "異常檢測",
        "subgraph_visualization": "子圖視覺化",
        "sort_type_label": "排序類型:",
        "flow_sort_total": "總流量",
        "flow_sort_https": "HTTPS",
        "flow_sort_outratio": "出流量",
        "outratio_threshold_label": "出流量佔比閾值:",
        "flow_sort_button": "執行流量排序",
        "path_type_label": "路徑類型:",
        "path_min_congestion": "最小壅塞",
        "path_min_hop": "最小跳數",
        "path_min_risk": "最小風險",
        "src_ip_label": "來源IP:",
        "dst_ip_label": "目的IP:",
        "compare_strategies_checkbox": "對比三種策略",
        "path_search_button": "搜尋路徑",
        "output_log_tab": "⚙️ 運行日誌",
        "output_table_tab": "📊 數據表格",
        "output_detail_tab": "🗺️ 路徑與詳情",
        "anomaly_tab_port_scan": "連接埠掃描",
        "anomaly_tab_ddos": "DDoS目標",
        "anomaly_tab_star": "星狀結構",
        "anomaly_tab_custom_rule": "自訂規則",
        "port_scan_threshold_label": "連接埠數閾值:",
        "port_scan_button": "檢測",
        "ddos_neighbor_threshold_label": "鄰居數閾值:",
        "ddos_traffic_threshold_label": "入流量閾值:",
        "ddos_traffic_placeholder": "例如：1024",
        "ddos_unit_bytes": "位元組",
        "ddos_button": "檢測",
        "star_threshold_label": "葉節點數閾值:",
        "star_button": "檢測",
        "subgraph_target_ip_label": "目標IP:",
        "subgraph_generate_button": "生成子圖",
        "open_file_dialog_title": "選擇資料檔案",
        "file_filter": "支援的檔案 (*.csv *.pcap *.json *.html);;CSV (*.csv);;PCAP (*.pcap);;JSON (*.json);;HTML (*.html)",
        "encoding_conversion_failed": "檔案編碼轉換失敗，無法載入！",
        "analyzing_data": "正在分析資料，請稍候...",
        "loaded_file": "已載入檔案: {}",
        "parsing_pcap": "正在解析 PCAP 檔案，請稍候...",
        "no_valid_ipv4_data": "PCAP 檔案未提取到有效 IPv4 資料",
        "error": "錯誤",
        "data_validity_check_failed": "檢查資料有效性失敗: {}",
        "task_start": "[{}] 🚀 開始執行任務: {}",
        "command_line": "[{}] 命令列: {}",
        "task_complete": "\n[{}] ✅ 任務執行完成！正在解析結果...",
        "task_full_graph": "全網拓撲",
        "task_subgraph": "子圖",
        "task_flow_sort": "流量排序",
        "task_min_congestion": "最小壅塞路徑",
        "task_min_hop": "最小跳數路徑",
        "task_min_risk": "最小風險路徑",
        "task_compare_paths": "路徑對比",
        "task_port_scan": "連接埠掃描檢測",
        "task_ddos_target": "DDoS目標檢測",
        "task_star_structures": "星狀結構查找",
        "task_custom_rule": "自訂規則檢測",
        "custom_rule_table_header_src_ip": "來源IP",
        "custom_rule_table_header_dst_ip": "目的IP",
        "custom_rule_table_header_protocol": "協定類型",
        "custom_rule_protocol_label": "協定類型:",
        "custom_rule_protocol_placeholder": "例如：6 (TCP)",
        "custom_rule_protocol_int": "協定類型必須為整數",
        "custom_rule_protocol_range": "協定類型必須是0-255之間的整數",
        "custom_rule_table_header_src_port": "來源埠",
        "custom_rule_table_header_dst_port": "目的埠",
        "custom_rule_table_header_reason": "違規原因",
        "flow_sort_table_header_ip": "IP位址",
        "flow_sort_table_header_total_traffic": "總流量（位元組）",
        "flow_sort_table_header_https_traffic": "HTTPS流量（位元組）",
        "flow_sort_table_header_out_ratio": "出流量佔比",
        "port_scan_table_header_ip": "IP位址",
        "port_scan_table_header_port_count": "不同目的埠數",
        "star_table_header_center_ip": "中心IP",
        "star_table_header_neighbor_count": "鄰居葉子數",
        "star_table_header_total_traffic": "總流量",
        "path_detail_title": "🔎 路徑分析結果",
        "path_detail_congestion_label": "壅塞值: {}",
        "path_detail_hop_label": "跳數: {}",
        "path_detail_risk_label": "風險值: {}",
        "path_found_count_congestion": "共找到 {} 條最小壅塞路徑：",
        "path_found_count_hop": "最小跳數為 {}，共找到 {} 條路徑：",
        "path_found_count_risk": "最小風險值為 {}，共找到 {} 條路徑：",
        "path_detail_not_found": "未找到符合條件的路徑。",
        "compare_paths_detail_title": "🔎 路徑對比結果",
        "compare_paths_min_hop_display": "最小跳數: {}",
        "compare_paths_min_risk_display": "最小風險值: {}",
        "compare_paths_table_header_strategy": "策略",
        "compare_paths_table_header_count": "路徑數量",
        "compare_paths_table_header_congestion_range": "壅塞值範圍(Min ~ Max)",
        "compare_paths_strategy_min_congestion": "最小壅塞",
        "compare_paths_strategy_min_hop": "最小跳數",
        "compare_paths_strategy_min_risk": "最小風險",
        "compare_paths_not_found": "未找到符合條件的路徑。",
        "compare_paths_congestion_label": "壅塞值: {}",
        "generate_html_json_invalid": "錯誤：JSON 檔案無效或未能成功產生。",
        "generate_html_theme_invalid": "無法產生圖表（JSON 檔案無效）",
        "generate_html_no_nodes": "圖中無任何節點，可能是資料檔案中未包含有效 IP 位址。",
        "generate_html_theme_no_data": "圖中無資料",
        "generate_html_read_failed": "讀取 JSON 檔案失敗: {}",
        "generate_html_parse_failed": "解析 JSON 失敗",
        "generate_html_rendering": "正在渲染圖表，請稍候...",
        "generate_html_success": "圖表渲染完成！",
        "generate_html_load_failed": "載入 HTML 失敗: {}",
        "replace_cdn_error": "替換CDN連結時出錯: {}",
        "display_html_file_not_exist": "錯誤：HTML 檔案不存在 - {}",
        "display_html_success": "子圖已載入……",
        "display_html_failed_try_browser": "載入 HTML 失敗: {}，正在使用系統瀏覽器開啟",
        "display_html_opened_in_browser": "子圖已在系統瀏覽器中開啟",
        "about_content": "網路流量分析與異常檢測系統\n華中科技大學網路空間安全學院 - 程式設計綜合課程設計\n版本 1.0 | 2026年3月\n基於C++和PyQt6\n ©2026 那，邊。版權所有。",
        "path_search_warning_title": "警告",
        "path_search_need_src_dst": "請輸入來源IP和目的IP",
        "ddos_warning_title": "警告",
        "ddos_traffic_must_be_int": "入流量閾值必須為整數",
        "subgraph_warning_title": "警告",
        "subgraph_need_target_ip": "請輸入目標IP",
        "subgraph_generating": "正在生成以 {} 為中心的子圖...",
        "custom_rule_target_ip_label": "目標IP:",
        "custom_rule_target_ip_placeholder": "例如：192.168.1.100",
        "custom_rule_ip_range_group": "IP範圍",
        "custom_rule_radio_cidr": "CIDR",
        "custom_rule_cidr_placeholder": "例如：192.168.1.0/24",
        "custom_rule_radio_start_end": "起始IP - 結束IP",
        "custom_rule_start_ip_placeholder": "起始IP",
        "custom_rule_to_label": "至",
        "custom_rule_end_ip_placeholder": "結束IP",
        "custom_rule_type_label": "規則類型:",
        "custom_rule_type_deny": "拒絕",
        "custom_rule_type_allow": "允許",
        "custom_rule_optional_group": "可選參數",
        "custom_rule_src_port_label": "來源埠:",
        "custom_rule_src_port_placeholder": "例如：443",
        "custom_rule_dst_port_label": "目的埠:",
        "custom_rule_dst_port_placeholder": "例如：80",
        "custom_rule_max_traffic_label": "最大流量閾值:",
        "custom_rule_max_traffic_placeholder": "例如：1024",
        "custom_rule_unit_bytes": "位元組",
        "custom_rule_button": "檢測違規記錄",
        "custom_rule_warning_title": "警告",
        "custom_rule_need_target_ip": "請輸入目標IP",
        "custom_rule_need_cidr": "請輸入CIDR範圍",
        "custom_rule_need_start_end": "請輸入起始IP和結束IP",
        "custom_rule_src_port_int": "來源埠必須為整數",
        "custom_rule_dst_port_int": "目的埠必須為整數",
        "custom_rule_max_traffic_int": "最大流量閾值必須為整數",
        "full_graph_exported": "全網拓撲已匯出到 {}",
        "subgraph_exported": "子圖已匯出到 {}",
        "port_scan_detected": "檢測到連接埠掃描攻擊者 {} 個:",
        "ddos_target_detected": "檢測到DDoS攻擊目標 {} 個:",
        "ddos_table_header_in_data": "入流量（位元組）",
        "ddos_table_header_neighbor_count": "鄰居數",
        "star_structure_found": "找到星狀結構 {} 個:",
        "custom_rule_violations": "違反規則的通訊記錄 {} 條:",
        "path_subgraph_exported": "路徑子圖已匯出到 {}",
        "compare_paths_subgraph_exported": "對比路徑子圖已匯出到 {}",
        "port_scan_subgraph_exported": "連接埠掃描攻擊者子圖已匯出到 {}",
        "ddos_subgraph_exported": "DDoS攻擊目標子圖已匯出到 {}",
        "star_subgraph_exported": "星狀結構子圖已匯出到 {}",
        "custom_rule_subgraph_exported": "違規通訊子圖已匯出到 {}",
        "no_path_found": "沒有找到從 {} 到 {} 的路徑",
        "min_congestion_paths": "最小壅塞路徑 (共 {} 條):",
        "min_hop_paths": "最小跳數路徑 (最小跳數 = {}):",
        "min_risk_paths": "最小風險路徑 (最小風險值 = {}):",
        "min_congestion_section": "【最小壅塞路徑】",
        "min_hop_section": "【最小跳數路徑】",
        "min_risk_section": "【最小風險路徑】",
        "no_violations": "  無違規記錄",
        "error_prefix": "錯誤: {}",
        "warning_prefix": "警告: {}",
        "subgraph_error_file_not_found": "錯誤：找不到檔案 {}",
        "subgraph_error_json_corrupted": "錯誤：JSON 格式損壞",
        "edge_traffic_title": "流量: {}",
        "violation_ip_range": "違反IP位址範圍規則",
        "violation_protocol": "協定類型{}違反規則",
        "violation_src_port": "來源埠{}違反規則",
        "violation_dst_port": "目的埠{}違反規則",
        "violation_traffic": "與{}的通訊流量為{} bytes，超過了最大流量閾值{} bytes",
        "view_only_mode_no_analysis": "目前處於視覺化檢視模式，無法進行分析操作。",
        "prepare_html_failed": "準備HTML顯示檔案失敗: {}",
        "visual_file_loaded": "已載入視覺化檔案: {}",
        "file_not_available": "要匯出的檔案不可用，請先產生對應圖。",
        "save_file": "儲存檔案",
        "{}_files": "{}檔案 (*{})",
        "export_menu": "匯出",
        "export_pcap_csv": "PCAP轉換的CSV",
        "export_current_subgraph": "當前子圖",
    },
    "en_US": {
        "app_title": "Network Traffic Analysis and Anomaly Detection System",
        "waiting_data": "Waiting for data analysis...",
        "waiting_data_loading": "Waiting for data loading...",
        "warning": "Warning",
        "src_port_int": "Source port must be an integer",
        "dst_port_int": "Destination port must be an integer",
        "max_traffic_int": "Max traffic threshold must be an integer",
        "settings": "Settings",
        "help": "Help",
        "about": "About",
        "help_manual": "User Manual",
        "language": "Language / 语言",
        "lang_zh_CN": "简体中文",
        "lang_zh_TW": "繁体中文",
        "lang_en_US": "English",
        "restart_required": "Language switched successfully. Some UI elements may require an app restart to take full effect.",
        "info": "Information",
        "invalid_data": "Invalid data",
        "data_not_loaded": "No data files have been loaded. Please load valid data first!",
        "empty_file": "The file being loaded is empty. Please try again!",
        "no_valid_network_data": "The file being loaded contains no valid network traffic data. Please try again!",
        "file": "File",
        "browse": "Browse...",
        "data_file": "Data File:",
        "open_file": "Open Data File",
        "thread_count": "Thread Count:",
        "traffic_sorting": "Traffic Sorting",
        "path_search": "Path Search",
        "anomaly_detection": "Anomaly Detection",
        "subgraph_visualization": "Subgraph Visualization",
        "sort_type_label": "Sort Type:",
        "flow_sort_total": "Total Traffic",
        "flow_sort_https": "HTTPS",
        "flow_sort_outratio": "Outgoing Ratio",
        "outratio_threshold_label": "Outgoing Ratio Threshold:",
        "flow_sort_button": "Run Traffic Sort",
        "path_type_label": "Path Type:",
        "path_min_congestion": "Min Congestion",
        "path_min_hop": "Min Hop",
        "path_min_risk": "Min Risk",
        "src_ip_label": "Source IP:",
        "dst_ip_label": "Destination IP:",
        "compare_strategies_checkbox": "Compare Three Strategies",
        "path_search_button": "Find Path",
        "output_log_tab": "⚙️ Run Log",
        "output_table_tab": "📊 Data Table",
        "output_detail_tab": "🗺️ Path & Details",
        "anomaly_tab_port_scan": "Port Scan",
        "anomaly_tab_ddos": "DDoS Target",
        "anomaly_tab_star": "Star Structure",
        "anomaly_tab_custom_rule": "Custom Rule",
        "port_scan_threshold_label": "Port Threshold:",
        "port_scan_button": "Detect",
        "ddos_neighbor_threshold_label": "Neighbor Threshold:",
        "ddos_traffic_threshold_label": "Incoming Traffic Threshold:",
        "ddos_traffic_placeholder": "e.g., 1024",
        "ddos_unit_bytes": "Bytes",
        "ddos_button": "Detect",
        "star_threshold_label": "Leaf Node threshold:",
        "star_button": "Detect",
        "subgraph_target_ip_label": "Target IP:",
        "subgraph_generate_button": "Generate Subgraph",
        "open_file_dialog_title": "Select Data File",
        "file_filter": "Supported files (*.csv *.pcap *.json *.html);;CSV (*.csv);;PCAP (*.pcap);;JSON (*.json);;HTML (*.html)",
        "encoding_conversion_failed": "File encoding conversion failed, cannot load!",
        "analyzing_data": "Analyzing data, please wait...",
        "loaded_file": "Loaded file: {}",
        "parsing_pcap": "Parsing PCAP file, please wait...",
        "no_valid_ipv4_data": "No valid IPv4 data extracted from PCAP file",
        "error": "Error",
        "data_validity_check_failed": "Data validity check failed: {}",
        "task_start": "[{}] 🚀 Start task: {}",
        "command_line": "[{}] Command line: {}",
        "task_complete": "\n[{}] ✅ Task completed! Parsing results...",
        "task_full_graph": "Full Graph",
        "task_subgraph": "Subgraph",
        "task_flow_sort": "Flow Sort",
        "task_min_congestion": "Min Congestion Path",
        "task_min_hop": "Min Hop Path",
        "task_min_risk": "Min Risk Path",
        "task_compare_paths": "Path Comparison",
        "task_port_scan": "Port Scan Detection",
        "task_ddos_target": "DDoS Target Detection",
        "task_star_structures": "Star Structure Detection",
        "task_custom_rule": "Custom Rule Detection",
        "custom_rule_table_header_src_ip": "Source IP",
        "custom_rule_table_header_dst_ip": "Destination IP",
        "custom_rule_table_header_protocol": "Protocol",
        "custom_rule_table_header_src_port": "Source Port",
        "custom_rule_table_header_dst_port": "Destination Port",
        "custom_rule_table_header_reason": "Reason",
        "flow_sort_table_header_ip": "IP Address",
        "flow_sort_table_header_total_traffic": "Total Traffic (Bytes)",
        "flow_sort_table_header_https_traffic": "HTTPS Traffic (Bytes)",
        "flow_sort_table_header_out_ratio": "Outgoing Ratio",
        "port_scan_table_header_ip": "IP Address",
        "port_scan_table_header_port_count": "Unique Destination Port Count",
        "star_table_header_center_ip": "Center IP",
        "star_table_header_neighbor_count": "Neighbor Leaf Count",
        "star_table_header_total_traffic": "Total Traffic",
        "path_detail_title": "🔎 Path Analysis Result",
        "path_detail_congestion_label": "Congestion: {}",
        "path_detail_hop_label": "Hop Count: {}",
        "path_detail_risk_label": "Risk: {}",
        "path_found_count_congestion": "Found {} min-congestion path(s):",
        "path_found_count_hop": "Min hops = {}, found {} path(s):",
        "path_found_count_risk": "Min risk = {}, found {} path(s):",
        "path_detail_not_found": "No matching path found.",
        "compare_paths_detail_title": "🔎 Path Comparison Result",
        "compare_paths_min_hop_display": "Min hops: {}",
        "compare_paths_min_risk_display": "Min risk: {}",
        "compare_paths_table_header_strategy": "Strategy",
        "compare_paths_table_header_count": "Path Count",
        "compare_paths_table_header_congestion_range": "Congestion Range (Min ~ Max)",
        "compare_paths_strategy_min_congestion": "Min Congestion",
        "compare_paths_strategy_min_hop": "Min Hop",
        "compare_paths_strategy_min_risk": "Min Risk",
        "compare_paths_not_found": "No matching path found.",
        "compare_paths_congestion_label": "Congestion: {}",
        "generate_html_json_invalid": "Error: JSON file is invalid or could not be generated.",
        "generate_html_theme_invalid": "Cannot generate graph (invalid JSON file)",
        "generate_html_no_nodes": "No nodes in the graph, possibly no valid IP addresses in the data file.",
        "generate_html_theme_no_data": "No data in graph",
        "generate_html_read_failed": "Failed to read JSON file: {}",
        "generate_html_parse_failed": "Failed to parse JSON",
        "generate_html_rendering": "Rendering graph, please wait...",
        "generate_html_success": "Graph rendering completed!",
        "generate_html_load_failed": "Failed to load HTML: {}",
        "replace_cdn_error": "Error replacing CDN links: {}",
        "display_html_file_not_exist": "Error: HTML file does not exist - {}",
        "display_html_success": "Subgraph loaded...",
        "display_html_failed_try_browser": "Failed to load HTML: {}, opening in system browser",
        "display_html_opened_in_browser": "Subgraph opened in system browser",
        "about_content": "Network Traffic Analysis and Anomaly Detection System\nSchool of Cyber Science and Engineering, Huazhong University of Science and Technology - Comprehensive Programming Course Design\nVersion 1.0 | March 2026\nBased on C++ and PyQt6\n ©2026 Na, Bian. All rights reserved.",
        "path_search_warning_title": "Warning",
        "path_search_need_src_dst": "Please enter source IP and destination IP",
        "ddos_warning_title": "Warning",
        "ddos_traffic_must_be_int": "Incoming traffic threshold must be an integer",
        "subgraph_warning_title": "Warning",
        "subgraph_need_target_ip": "Please enter target IP",
        "subgraph_generating": "Generating subgraph centered at {}...",
        "custom_rule_target_ip_label": "Target IP:",
        "custom_rule_target_ip_placeholder": "e.g., 192.168.1.100",
        "custom_rule_ip_range_group": "IP Range",
        "custom_rule_radio_cidr": "CIDR",
        "custom_rule_cidr_placeholder": "e.g., 192.168.1.0/24",
        "custom_rule_radio_start_end": "Start IP - End IP",
        "custom_rule_start_ip_placeholder": "Start IP",
        "custom_rule_to_label": "to",
        "custom_rule_end_ip_placeholder": "End IP",
        "custom_rule_type_label": "Rule Type:",
        "custom_rule_type_deny": "Deny",
        "custom_rule_type_allow": "Allow",
        "custom_rule_optional_group": "Optional Parameters",
        "custom_rule_src_port_label": "Source Port:",
        "custom_rule_src_port_placeholder": "e.g., 443",
        "custom_rule_dst_port_label": "Destination Port:",
        "custom_rule_dst_port_placeholder": "e.g., 80",
        "custom_rule_max_traffic_label": "Max Traffic Threshold:",
        "custom_rule_max_traffic_placeholder": "e.g., 1024",
        "custom_rule_unit_bytes": "Bytes",
        "custom_rule_button": "Detect Violations",
        "custom_rule_warning_title": "Warning",
        "custom_rule_need_target_ip": "Please enter target IP",
        "custom_rule_need_cidr": "Please enter CIDR range",
        "custom_rule_need_start_end": "Please enter start IP and end IP",
        "custom_rule_protocol_label": "Protocol:",
        "custom_rule_protocol_placeholder": "e.g., 6 (TCP)",
        "custom_rule_protocol_int": "Protocol must be an integer",
        "custom_rule_protocol_range": "Protocol must be between 0 and 255",
        "custom_rule_src_port_int": "Source port must be an integer",
        "custom_rule_dst_port_int": "Destination port must be an integer",
        "custom_rule_max_traffic_int": "Max traffic threshold must be an integer",
        "full_graph_exported": "Full graph exported to {}",
        "subgraph_exported": "Subgraph exported to {}",
        "port_scan_detected": "Detected {} port scanner(s):",
        "ddos_target_detected": "Detected {} DDoS target(s):",
        "ddos_table_header_in_data": "Incoming Traffic (Bytes)",
        "ddos_table_header_neighbor_count": "Neighbor Count",
        "star_structure_found": "Found {} star structure(s):",
        "custom_rule_violations": "{} violation record(s):",
        "path_subgraph_exported": "Path subgraph exported to {}",
        "compare_paths_subgraph_exported": "Comparison paths subgraph exported to {}",
        "port_scan_subgraph_exported": "Port scanner subgraph exported to {}",
        "ddos_subgraph_exported": "DDoS target subgraph exported to {}",
        "star_subgraph_exported": "Star structure subgraph exported to {}",
        "custom_rule_subgraph_exported": "Violation subgraph exported to {}",
        "no_path_found": "No path found from {} to {}",
        "min_congestion_paths": "Min congestion paths ({} found):",
        "min_hop_paths": "Min hop paths (min hops = {}):",
        "min_risk_paths": "Min risk paths (min risk = {}):",
        "min_congestion_section": "【Min Congestion Path】",
        "min_hop_section": "【Min Hop Path】",
        "min_risk_section": "【Min Risk Path】",
        "no_violations": "  No violations",
        "error_prefix": "Error: {}",
        "warning_prefix": "Warning: {}",
        "subgraph_error_file_not_found": "Error: File not found {}",
        "subgraph_error_json_corrupted": "Error: JSON format corrupted",
        "edge_traffic_title": "Traffic: {}",
        "violation_ip_range": "Violates IP range rule",
        "violation_protocol": "Protocol {} violates rule",
        "violation_src_port": "Source port {} violates rule",
        "violation_dst_port": "Destination port {} violates rule",
        "violation_traffic": "Traffic with {} is {} bytes, exceeding max threshold {} bytes",
        "view_only_mode_no_analysis": "Currently in view-only mode. Analysis operations are disabled.",
        "prepare_html_failed": "Failed to prepare HTML display file: {}",
        "visual_file_loaded": "Visualization file loaded: {}",
        "file_not_available": "The file to export is not available. Please generate the corresponding graph first.",
        "save_file": "Save File",
        "{}_files": "{} files (*{})",
        "export_menu": "Export",
        "export_pcap_csv": "CSV Converted From PCAP",
        "export_current_subgraph": "Current Subgraph",
    }
}


class LanguageManager(QObject):
    """语言管理器：负责保存、读取当前语言设置并通知界面更新"""
    language_changed = pyqtSignal()

    def __init__(self, config_file="lang_config.json"):
        super().__init__()
        self.config_file = config_file
        self.current_lang = "zh_CN"
        self.load_config()

    def load_config(self):
        if os.path.exists(self.config_file):
            try:
                with open(self.config_file, 'r', encoding='utf-8') as f:
                    config = json.load(f)
                    self.current_lang = config.get("language", "zh_CN")
            except Exception as e:
                print(f"读取语言配置失败: {e}")

    def save_config(self):
        config = {"language": self.current_lang}
        try:
            with open(self.config_file, 'w', encoding='utf-8') as f:
                json.dump(config, f)
        except Exception as e:
            print(f"保存语言配置失败: {e}")

    def set_language(self, lang):
        if lang in TRANSLATIONS and lang != self.current_lang:
            self.current_lang = lang
            self.save_config()
            self.language_changed.emit()

    def tr(self, key, default=None):
        return TRANSLATIONS.get(self.current_lang, {}).get(key, default or key)


# 全局单例
lang_mgr = LanguageManager()


# 快捷翻译函数
def tr(key, default=None):
    return lang_mgr.tr(key, default)
